title: Timothy Manuel
logo: /assets/profilepic.jpeg
description: Goal-oriented marketing analyst with strong technical skills in SQL, data aggregation, and analytics dashboards. Proven unique background rooted in a client-first attitude and results-driven mindset. Committed to improving workplace efficiency by providing accurate and organized data.
#show_downloads: true
theme: jekyll-theme-minimal
