title: Timothy Manuel
logo: /assets/image.png
description: Hello! I am a marketing analyst with strong technical skills in SQL, data aggregation, and analytics dashboards. I believe that data is the most important thing that drives businesses behind the scenes. With data, a company can know its standing in the field.

#show_downloads: true
theme: jekyll-theme-minimal
